ERROR:root:Error at 2016-05-14 16:42:09.170174
Traceback (most recent call last):
  File "quickdeployv2.py", line 43, in <module>
    main()
  File "quickdeployv2.py", line 15, in main
    check(UserAns, directory, sections,ini)
  File "quickdeployv2.py", line 25, in check
    main()
  File "quickdeployv2.py", line 15, in main
    check(UserAns, directory, sections,ini)
  File "quickdeployv2.py", line 31, in check
    sys.exit()
SystemExit
ERROR:root:Error at 2016-05-14 16:44:27.546363
Traceback (most recent call last):
  File "quickdeployv2.py", line 43, in <module>
    main()
  File "quickdeployv2.py", line 15, in main
    check(UserAns, directory, sections,ini)
  File "quickdeployv2.py", line 31, in check
    sys.exit(1)
SystemExit: 1
ERROR:root:Error at 2016-05-14 16:44:38.562849
Traceback (most recent call last):
  File "quickdeployv2.py", line 43, in <module>
    main()
  File "quickdeployv2.py", line 15, in main
    check(UserAns, directory, sections,ini)
  File "quickdeployv2.py", line 31, in check
    sys.exit(0)
SystemExit: 0
ERROR:root:Error at 2016-05-14 16:45:26.211622
Traceback (most recent call last):
  File "quickdeployv2.py", line 43, in <module>
    main()
  File "quickdeployv2.py", line 15, in main
    check(UserAns, directory, sections,ini)
  File "quickdeployv2.py", line 31, in check
    sys.exit(1)
SystemExit: 1
